name: Build and Push Docker Image to ACR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "App version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZURE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/planningpoker:${{ steps.get_version.outputs.version }} .
          docker push ${{ secrets.AZURE_REGISTRY }}/planningpoker:${{ steps.get_version.outputs.version }}
