name: Deploy Image from ACR to Azure Web App

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ACR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "App version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ vars.AZURE_REGISTRY }}/planningpoker:${{ steps.get_version.outputs.version }}
